Create readme file
PGS-php/upskilling-2nd-edition pull request #3
Opened 2017-12-05 19:26 UTC by dominikhajduk

2017-12-12 21:01 UTC, partikus requested changes

2017-12-12 21:01 UTC, partikus commented on README.md
> +    docker-compose up
missing code block

2017-12-12 21:01 UTC, partikus commented on README.md
> +See [CONTRIBUTING.md](CONTRIBUTING.md)
please add license as well

2017-12-12 21:06 UTC, dominikhajduk commented on README.md
> +    docker-compose up
4 spaces will be changed to code block

2017-12-12 21:06 UTC, dominikhajduk commented on README.md
> +See [CONTRIBUTING.md](CONTRIBUTING.md)
updated

2017-12-12 22:21 UTC, mateuszmaslanka commented on README.md
> +    docker-compose up
IMO` ```bash`

2017-12-13 19:25 UTC, dominikhajduk commented
@mateuszmaslanka @partikus improved

2017-12-15 07:22 UTC, tarnawski approved these changes
Looks nice. Thanks for update!

2017-12-15 07:55 UTC, tarnawski commented
@partikus pls check again

2017-12-15 14:42 UTC, partikus commented on README.md
> +    docker-compose up
useless indentation

2017-12-15 14:43 UTC, partikus approved these changes

2017-12-15 15:02 UTC, merged